# Generated by Django 4.2.4 on 2023-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0003_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
